name: meuapppdv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_multi_formatter: ^2.9.0
  provider: ^6.1.5+1
  email_validator: ^2.0.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\logo.png
