name: medshift
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_multi_formatter: ^2.13.10
  provider: ^6.1.5
  email_validator: ^3.0.0
  http: ^1.6.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2

  stream_chat_flutter: ^9.20.0
  stream_chat: ^9.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\logo.png
